# It's Micro, for exit use Ctrl+Q, for save - Ctrl+S
[settings]
wm = "auto" # or your WM but with a capital letter
wm_type = "auto" # auto (don't work with unregistred WM) | workspaces | coordinates
mainRad = 10 # 0-25
barOnTop = true
minibar = false
barHeight = 30
fontSize = 17
fontFamily = "Mononoki Nerd Font Propo"
custom_wallpaper_engine = false
doNotDistrub = false

# [plugin.name]
# source = "plugin-example/Main.qml"
# active = true
