[settings]
wm = "auto" # or your WM but with a capital letter
wm_type = "auto" # auto (don't work with unregistred WM) | workspaces | coordinates
mainRad = 10 # 0-25
barOnTop = true
minibar = false
barHeight = 30
fontSize = 17
fontFamily = "Mononoki Nerd Font Propo"

# [[plugin]]
# name = "plugin name"
# source = "plugin directory/main file.qml"
# active = true
