backend = "wal"
color_space = "lch"
palette = "soft-dark"
# skip_sequences = true

[templates]
quickshell = { template = 'quickshell.json', target = '~/.config/quickshell/colors.json' }
sway = { template = 'sway', target = '~/.config/sway/colors.conf' }

[hooks]
sway = "swaymsg reload"
# notif = 'notify-send "New Scheme Generated!"'
