[bell]
system=yes
notify=yes
urgent=yes

[colors-dark]
alpha=1.0
# ФОН — ОСТАВЛЯЕМ (Matugen с фильтрами)
background={{ colors.surface_container.default.hex_stripped | lighten:11 | set_saturation:7 }}

# ТЕКСТ (Zenburn)
foreground=dcdccc

# ОСНОВНЫЕ ЦВЕТА (Zenburn)
regular0=3f3f3f
regular1=dca3a3
regular2=b5cda3
regular3=e3c9a3
regular4=8cb3d9
regular5=d3b0d0
regular6=9fc5c4
regular7=dcdccc

# ЯРКИЕ ЦВЕТА (Zenburn)
bright0=4f4f4f
bright1=dca3a3
bright2=b5cda3
bright3=e3c9a3
bright4=8cb3d9
bright5=d3b0d0
bright6=9fc5c4
bright7=dcdccc

# DIM — ОСТАВЛЯЕМ КАК ЕСТЬ (они уже жёсткие)
dim0=45475A 
dim1=F38BA8 
dim2=A6E3A1 
dim3=F9E2AF 
dim4=89B4FA 
dim5=F5C2E7 
dim6=94E2D5 
dim7=BAC2DE 

# ВЫДЕЛЕНИЕ — ОСТАВЛЯЕМ (Matugen с фильтрами)
selection-background={{ colors.outline_variant.default.hex_stripped }}
selection-foreground={{ colors.primary.default.hex_stripped}}

[cursor]
blink=no
style=block

[key-bindings]
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v

[main]
dpi-aware=no
font=Mononoki Nerd Font Propo:size=13
initial-color-theme=dark
pad=7x7
resize-by-cells=no
shell=bash
term=foot

[mouse]
hide-when-typing=yes

[scrollback]
lines=15000
