theme = "matugen"

[editor]
line-number = "relative"
mouse = true
auto-save = true
auto-info = true

[editor.lsp]
display-messages = false
display-inlay-hints = false

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

